name: Migrate GitHub Secrets to Vault 

on: 
  workflow_dispatch:
    inputs:
      logLevel: 
        description: 'Log level'
        required: true 
        default: 'warning'

jobs: 
  migrate-secret: 
    runs-on: ["self-hosted", "ub22"]
    steps: 
      
      - name: Checkout 
        uses: actions/checkout@v2 

      - name: Migrate Secret to Vault 
        uses: hashicorp/vault-action@v2.3.0 
        with: 
          url: 'https://vault.thecodemountains.com:8443'
          token: ${{ secrets.VAULT_TOKEN }}
          method: kv-v2
          path: 'secret/api-keys'
          secrets: |
            github_secret=${{ secrets.CM_GITHUB_TOKEN }}
          