name: Migrate GitHub Secrets to Vault 

on: 
  workflow_dispatch:
    inputs:
      logLevel: 
        description: 'Log level'
        required: true 
        default: 'warning'

jobs: 
  migrate-secret: 
    runs-on: ["self-hosted", "ub22"]
    steps: 
      
      - name: Checkout 
        uses: actions/checkout@v2 

      - name: Check if Secret is Empty 
        run: |
          if [ -z "${{ secrets.VAULT_ADDR }}" ]; then
            echo "VAULT_ADDR is empty"
            exit 1
          else
            echo "VAULT_ADDR is set"
          fi

      - name: Migrate using Vault CLI 
        run: |
          vault kv put ci/kvv2/vault VAULT_ADDR="${{ secrets.VAULT_ADDR }}"   
        env: 
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}