name: Redeploy HashiCorp Vault service

on:
  workflow_dispatch:
    inputs:
      logLevel: 
        description: 'Log level'
        required: true 
        default: 'warning'
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  redeploy_vault:
    runs-on: ["self-hosted", "ub22"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Vault Address
        run: echo "VAULT_ADDR=${{ secrets.VAULT_ADDR }}" >> $GITHUB_ENV

      - name: Redeploy Vault using Nginx
        run: |
          # Restart our Vault service and Nginx
          echo "Restarting Vault service, Nginx web server and reverse proxy"        
          sudo systemctl daemon-reload 
          sudo systemctl restart vault        
          sudo systemctl restart nginx
          echo "SUCCESS: Services restarted."        

      - name: Unseal Vault
        run: |
          VAULT_ADDR='https://vault.thecodemountains.com:8443'
          echo $VAULT_ADDR

          vault operator unseal 3cqfflastAvaefmkxtKf/Z8MN/64zgXj6YjFRg+QVIhC
          vault operator unseal TaRPcXBpNruJWJKFJJ5ShpCfQMBVj2vltRK4t38fTOeS
          vault operator unseal HkGw2PZM1ZjfSNZiUJGQJlj+pwsbBbwhArpr4DHYEqDJ

          echo "SUCCESS: Vault unsealed successfully"
          vault status
