name: Redeploy HashiCorp Vault service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  redeploy_vault:
    runs-on: ["self-hosted","ub22"]  

    steps:

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Redeploy Vault using Nginx 
      run: |
        # Restart our Vault service and Nginx
        echo "Restarting Vault service, Nginx web server and reverse proxy"        
        sudo systemctl daemon-reload 
        sudo systemctl restart vault 
        echo "SUCCESS: services restart successfully!"        
        sudo systemctl restart nginx
        sudo systemctl status vault
        sudo systemctl status nginx
        
